USE BackboneTier3;
DROP TABLE IF EXISTS GeneratorStatus;
CREATE TABLE GeneratorStatus
(
	Id INT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
	InsertedTS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

	GeneratedId varchar(8) NOT NULL,

	KEY (Id)
);
ALTER TABLE GeneratorStatus ADD CONSTRAINT PK_Id PRIMARY KEY(Id);
